services:

  email-intake-engine:
    deploy_type: appservice

  quote-service:
    deploy_type: appservice

  job-service:
    deploy_type: appservice

  crm-service:
    deploy_type: appservice

  finance-service:
    deploy_type: appservice
