name: Push ACR

on:
  workflow_call:

    inputs:
      service_name:
        required: true
        type: string

jobs:

  push:

    runs-on: ubuntu-latest

    environment: uat

    steps:

      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login ACR
        run: |

          az acr login \
          --name ${{ vars.ACR_NAME }}

      - name: Build Image
        run: |

          docker build \
            -t ${{ vars.ACR_NAME }}.azurecr.io/${{ inputs.service_name }}:${{ github.sha }} \
            ./services/${{ inputs.service_name }}

      - name: Push Image
        run: |

          docker push \
            ${{ vars.ACR_NAME }}.azurecr.io/${{ inputs.service_name }}:${{ github.sha }}
